server:
  port: 8882
  contextPath: /account-service
  address: 127.0.0.1


spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://45.32.254.172:3306/myth_account?useUnicode=true&characterEncoding=utf8
        username: admin
        password: admin
        initialSize: 20
        minIdle: 20
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    application:
      name: account-service
   #activemq:
        #   broker-url: tcp://120.76.52.162:61616
        #   user: happylife
        #   password: happylifeplat01
        #   trust-all: true
    rabbitmq:
            host: 45.32.254.172
            port: 5672
            username: mqadmin
            password: mqadmin
#    rocketmq:
#          namesrvAddr: localhost:9876
#          consumerGroupName: account
#          instanceName: account
   #kafka:
          #  consumer:
          #     bootstrap-servers: localhost:9092
          #     group-id: test
          #     auto-offset-reset: earliest
          #     enable-auto-commit: true
          #     auto-commit-interval: 100
          #    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          #     value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

mybatis:
  type-aliases-package: com.github.myth.demo.springcloud.account.api.entity
  config-location: classpath:mybatis/mybatis-config.xml
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/

com:
  github :
      myth :
        serializer : kryo
        repositorySupport : db
        mythDbConfig :
                 driverClassName  : com.mysql.jdbc.Driver
                 url :  jdbc:mysql://45.32.254.172:3306/myth?useUnicode=true&amp;characterEncoding=utf8
                 username : admin
                 password : admin
#        repositorySupport : redis
#                 hostName  : 45.32.254.172
#                 port : 6379
#                 password :
#        repositorySupport : redis
#                hostName  : 45.32.254.172
#                port      :  6379
#                password  :


       # repositorySupport : zookeeper
       #         host      : 192.168.1.73:2181
       #         sessionTimeOut      :  100000
       #         rootPath  : /myth

       # repositorySupport : mongodb
       #       mongoDbUrl  : 192.168.1.68:27017
       #       mongoDbName  :  youname
       #       mongoUserName  : xiaoyu
       #       mongoUserPwd   : 123456

       # repositorySupport : file
       #         path      : /youpath
       #         prefix    :  youpath




account-service :
   ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        com.github.myth.bonuspoint: info
        com.github.myth.lottery: debug
        com.github.myth: debug

    path: "./logs"

